workflows:
  ios-deployment:
    name: Codemagic Sample Workflow
    max_build_duration: 30
    instance_type: mac_mini_m1
    working_directory: budget
    integrations:
      app_store_connect: CodeMagic
    environment:
      flutter: 3.13.6
      cocoapods: default
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.budget.tracker-app
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Install dependencies
        script: |
          flutter pub get
          if [ -f "ios/Podfile" ]; then
            pod install --project-directory=ios
          fi
      - name: Build IPA
        script: |
          flutter build ipa --release \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      - budget/build/ios/ipa/*.ipa
      - budget/tmp/xcodebuild_logs/*.log
      - budget/flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration 
        submit_to_testflight: true
        expire_build_submitted_for_review: false
        submit_to_app_store: false
